services:
  rag-manuals:
    container_name: ai-manuals-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped